#!/bin/bash

usage () {
	echo "usage: $0 [-u]"
	echo ""
	echo " -u option to unzip file after downloading"
	exit 1
}

if [ "$#" -gt 1 ]; then
	usage
fi
if [ "$#" -eq 1 ]; then
	if [ "$1" = "-u" ]; then
		UNZIP=true
	fi
fi
LAST=$(ssh sandbox "ls -1tr /schift/output | grep '.zip$' | tail -1")
if [ -z "$LAST" ]
then
	echo "No output found in sandbox."
	exit 1
else
	scp sandbox:/schift/output/$LAST .
fi
if [ "$UNZIP" = true ]; then
	unzip -u -d out $LAST
fi
